//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiComponents.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TouristPlace()
        {
            this.ImageFiles = new HashSet<ImageFile>();
        }
    
        public int PlaceId { get; set; }
        public string PlaceName { get; set; }
        public int Pincode { get; set; }
        public string States { get; set; }
        public string Significance { get; set; }
        public string Descriptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageFile> ImageFiles { get; set; }
    }
}
