//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportLib.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> RouteNumber { get; set; }
    
        public virtual SamsungEmployee SamsungEmployee { get; set; }
        public virtual RouteName RouteName { get; set; }
    }
}
