//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportLib.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        public string PickUp { get; set; }
        public string DropOut { get; set; }
        public Nullable<int> RouteNumber { get; set; }
        public decimal TicketAmount { get; set; }
    
        public virtual RouteName RouteName { get; set; }
    }
}
